### ISSUE TITLE
feat: pincode component for login and logout added.

### ISSUE THREAD

**Issue by hastebrot** [hastebrot/2024-gastro#1]
| original estimate | estimate | actual effort | remaining effort |
|--|--|--|--|
| 4h | 4h | 2h30m  | 1h30m  |

**acceptance criteria:**
- we have a pincode component that shows a number block
- each number is a button that can be pressed
- it shows 4 dots above the number block which indicates how many digits were entered
- we have a clear button that resets the pincode input
- after 4 digits were entered it resets the pincode input
- it shows "enter your PIN" on top

**task breakdown:**
- [x] create `PincodeInput` component and a `PincodeInputButton` component [1h30m]
- [x] when digit button was pressed, then update state of entered digits [30m]
- [x] add `PincodeDots` component and use entered digits to update the highlighted dots state [30m]
- [x] when clear button was pressed, then empty state of entered digits [30m]
- [x] add callback react prop that is called when entered digits reaches `requiredDigits`, and empty state of entered digits [30m]
- [ ] pull request, review, deployment [30m]

**technical details:**
- it needs react props to define a callback function for entered pincodes
- also `requiredDigits` number prop which defaults to `4`

**out of scope:**
- automatic resizing of component according to screen size. later, it should fill out the grid cell
