### ISSUE TITLE
feat: admin page with staff roaster

### ISSUE THREAD

**Issue by hastebrot** [hastebrot/2024-gastro#5]
| original estimate | estimate | actual effort | remaining effort |
|--|--|--|--|
| 6h | 4h | 2h30m | 0h |

**acceptance criteria:**
- we have an admin page that can be reached with admin pincode
- this admin page shows a table with the staff roaster
- it shows a back button to go back to the dashboard (the pincode needs to be entered again)
- the table contains rows for staff members
- the table contains columns for calendar week days
- the current calendar week is shown
- there is a navigation component to navigate to today, previous week and next week. label for the current week

**task breakdown:**
- [x] create new admin page. add routing from dashboard page to admin page after pincode was entered. add back button to route back from admin page to dashboard page [30m]
- [x] add table component with rows and columns. prefill rows with enumerated staff members. show staff member avatar icon with single letter [1h]
- [x] calculate the current week, selected week and days of the week. show them in the table columns [1h]
- [x] add calendar week navigation component [1h]
- [x] pull request, review, deploy [30m]

**technical details:**
- it's a tabular component with workers as row and day as columns
- we need navigation components for calender week

**open questions:**
- where do we manage the pincodes per worker?

**out of scope:**
- changing the order of workers (i.e. table rows) using drag-and-drop
- per row summary table column (staff member)
- per column summary table row (calendar week day)
- show the opening times per store in the table header row
